# Generated by Django 4.1 on 2023-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_updated_at_alter_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="post",
            name="birth",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="post",
            name="hobby",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="post",
            name="information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="need",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url1",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="url2",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
