# Generated by Django 4.1 on 2023-01-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_created_at_remove_post_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="file",
        ),
        migrations.AddField(
            model_name="post",
            name="birth",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
