# Generated by Django 4.1 on 2023-01-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_bool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bool",
        ),
        migrations.AddField(
            model_name="post",
            name="b",
            field=models.BooleanField(default=1, verbose_name="a"),
            preserve_default=False,
        ),
    ]
