# Generated by Django 4.1 on 2023-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hobby",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="need",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url1",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="url2",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
