# Generated by Django 4.1 on 2023-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("information", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("birth", models.CharField(max_length=6)),
                ("hobby", models.TextField(blank=True)),
                ("need", models.TextField(blank=True)),
                ("url1", models.URLField()),
                ("url2", models.URLField()),
            ],
        ),
    ]
