# Generated by Django 4.1 on 2023-01-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_file_post_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bool",
            field=models.BooleanField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
